### ISSUE TITLE
Any plans to publish to NPM?

### ISSUE THREAD

**Issue by FractalHQ** [relm-us/svelt-yjs#1]
I'm trying to figure out how to add this to an existing project of mine :)

**Comment by canadaduane** [comment]
Yes! It has already been published: https://www.npmjs.com/package/svelt-yjs

**Comment by FractalHQ** [comment]
Hah!  Awesome.  I forgot to drop the *e* 🤦‍♂️.  I'm excited to try this out.  I want to see how far I can get with a real-time collaborative DAW using web audio api.  Thanks!
